# Site
repository: JiYoonKimjimmy/RESUME
# favicon: images/favicon.ico

# Personal info
name: 김지윤
title: Back-End 개발자
# email: jimmyberg.kim@gmail.com
# website: jiyoonkimjimmy.github.io

# Social links
github_username: JiYoonKimjimmy
# twitter_username: jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: jim-kim-7001451b5
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  * Phone : 010 - 2032 - 6457
  * Email : jimmyberg.kim@gmail.com
  * Blog : jiyoonkimjimmy.github.io
  * Github : https://github.com/JiYoonKimjimmy

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
