# Site
repository: JiYoonKimjimmy/RESUME
# favicon: images/favicon.ico

# Personal info
name: 김지윤
title: Back-End 개발자
# email: jimmyberg.kim@gmail.com
# website: jiyoonkimjimmy.github.io

# Social links
github_username: JiYoonKimjimmy
# twitter_username: jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: jim-kim-7001451b5
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  #### Introduce,
  * 생년 월일 : 1990년 03월 09일
  * 최종 학력 : 수원대학교 정보통신공학과

  #### Contact,
  * Phone : 010 - 2032 - 6457
  * Email : jimmyberg.kim@gmail.com
  * Blog : jiyoonkimjimmy.github.io
  * Github : https://github.com/JiYoonKimjimmy

  <br>

  ---

  <br>

  #### Back-End 개발자로서,
  첫 개발의 시작은 다양한 금융 Application 개발 프로젝트를 통해 **Front-End & Back-End** 개발이였습니다. 이런 경험을 통해 프론트엔드와 백엔드 개발을 모두 할 수 있는 풀스택 개발자라는 장점을 있었지만, 프로젝트 진행하면서 서비스를 구성하는 전체 인프라 구조와 시스템 아키텍처에 대한 관심이 높아졌고, **전문적인 백엔드 개발자**가 되고 싶다는 욕심이 가지게 되었습니다.
  <br><br>
  현재는 백엔드 개발자로서 단순히 서비스 `REST API` 개발하고 제공하는 것뿐 아니라, 높은 트래픽을 고려한 작은 코딩부터 오픈 소스 미들웨어를 활용하여 시스템 부하를 줄일 수 있도록 도와주는 인프라 구성에도 관심을 가지고 집중하여 운영 환경에 반영하기 위해 노력하고 있습니다.
  <br><br>
  모든 개발자가 그렇듯이, 새로운 것에 항상 도전하는 의지로 기초적인 개발 기술일지라도 `A` 부터 `Z` 까지 차근차근 배우고 익혀가는 것과 다양한 경험을 토대로 학습한 기술력을 최대 활용하는 것을 즐기고 좋아합니다. 좋은 가독성, 편한 유지 보수성, 사이드 장애가 없는 서비스를 개발하기 위해 노력하고 있습니다.
  <br><br>
  **사막을 묵묵히 한 발짝씩 건너가는 낙타처럼, 느릴 수도 있지만 목표를 향해 정확하게, 그리고 끝까지 나아갈 수 있는 개발자가 되는 것이 저의 꿈입니다.**

  <br>

  ---

  <br>

  #### 새로운 개발 패러다임 Reactive Programming 적용기,
  최근 코나카드 결제 플랫폼 시스템을 외부 제휴사에 손쉬운 제공과 적용을 위해 `OpenAPI` 시스템 환경 구축 프로젝트에 참여하여 `APIGateway` 서버를 개발하고 있습니다. 해당 `APIGateway` 기능은 API 라우팅과 인가/인증, Access Key 관리, 암호화 Key 관리 등 `OpenAPI` 시스템의 중요한 부분을 담당하고 있습니다. `Spring Cloud Gateway` 를 활용한 `APIGateway` 서버 개발 하면서 `Webflux` 기반의 **Reactive Programming** 을 접하게 되었습니다.

  기존 선언적 프로그래밍 패러다임과 다른 함수형 프로그래밍 개념부터 반응형 프로그래밍까지 학습 없이는 힘들다는 생각이 들었습니다. 다행히 작년에 토이 프로젝트로 `Spring Webflux` 사용해본 경험을 토대로 팀원들과 짧은 2주간 `Webflux` 와 함수형/반응형 프로그래밍에 대해 스터디를 주도하여 `Observer` 패턴부터 함수형 프로그래밍의 1급 객체, 람다 등 기초적인 지식부터 시작하여 함수형 프로그래밍에 대해 학습하고 공유하였습니다.

  짧은 2주였지만 강렬하게 스터디하였고, Async & Non-Blocking 기반  `APIGateway` 서버를 개발하였고, 아직 서비스 오픈 전이지만 성능 테스트 결과 기존 `Spring Cloud Zuul` 기반의 `APIGateway` 에 비해 *미미한(?)* 성능에 대한 효과를 볼 수 있었습니다.

  함수형 프로그래밍 패러다임이라는 새로운 개발 패러다임을 직접 개발하면서, 순수 함수가 왜 더 `Side-effect` 부수 효과를 방지할 수 있는지, 이러한 점이 유지 보수 차원에서의 이점을 가져올 수 있었는지 알 수 있었습니다.

  위 프로젝트 경험처럼 새로운 시스템을 구축할 때, 용도에 맞는 기술 스펙을 선정하고, 새로운 기술에 대해 첫 단추부터 차근차근 채워가는 것이 얼마나 중요한지를 깨닫고 체득하였습니다. 또한 성공적인 협업을 위해서 함께 일하는 동료들과 학습해가는 방식과 지식 공유 등 함께 성장할 수 있는 개발의 즐거움도 느끼게 되었습니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
