# Site
repository: JiYoonKimjimmy/RESUME
# favicon: images/favicon.ico

# Personal info
name: 김지윤
title: Back-End 개발자
# email: jimmyberg.kim@gmail.com
# website: jiyoonkimjimmy.github.io

# Social links
github_username: JiYoonKimjimmy
# twitter_username: jekyll
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
linkedin_username: jim-kim-7001451b5
# pinterest_username: jekyll
# youtube_username: jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: |
  #### Introduce,
  * 생년 월일 : 1990년 03월 09일
  * 최종 학력 : 수원대학교 정보통신공학과

  #### Contact,
  * Phone : 010 - 2032 - 6457
  * Email : jimmyberg.kim@gmail.com
  * Blog : jiyoonkimjimmy.github.io
  * Github : https://github.com/JiYoonKimjimmy

  <br>

  ---

  <br>

  #### Back-End 개발자로서,
  <br>
  첫 개발의 시작은 다양한 금융 Application 개발 프로젝트를 통해 **Front-End & Back-End** 개발이였습니다.
  이런 경험을 통해 프론트엔드와 백엔드 개발을 모두 할 수 있는 풀스택 개발자라는 장점을 있었지만,
  다양한 프로젝트 진행하면서 서비스를 구성하는 전체 인프라 구조와 시스템 아키텍처에 대한 관심이 높아지면서, **전문성을 가진 백엔드 개발자**가 되고 싶다는 욕심이 가지게 되었습니다.
  <br><br>
  현재는 백엔드 개발자로서 단순히 서비스 API 개발하는 것뿐 아니라, 높은 트래픽을 고려한 작은 코드부터 오픈소스 라이브러리 또는 프레임워크를미들 활용한
  분산 시스템 구축을 고려하고, 트래픽 부하를 낮출 수 있는 인프라 구성에도 관심을 가지고 운영 환경에 개선하기 위해 노력하고 있습니다.
  <br><br>
  모든 개발자가 그렇듯이, 새로운 것에 항상 도전하는 의지로 기초적인 개발 기술일지라도 `A` 부터 `Z` 까지 차근차근 배우고 익혀가는 것과
  다양한 경험을 토대로 학습한 기술을 최대 활용하는 것을 즐기고, 습득한 경험을 동료들과 함께 공유하는 것에 재미를 느끼고 있습니다.
  <br><br>
  **사막을 묵묵히 한 걸음씩 건너가는 낙타처럼, 느릴 수도 있지만 목표를 향해 정확하게, 그리고 끝까지 나아갈 수 있는 개발자가 되는 것이 저의 꿈입니다.**

  <br>

  ---

  <br>

  #### 새로운 개발 패러다임 Reactive Programming 적용기,
  <br>
  2022년 코나카드 결제 플랫폼 시스템을 제휴 계약을 체결한 제휴 서비스에서 손쉬운 연동과 시스템 이용을 위해 `OpenAPI` 시스템 환경 구축 프로젝트를 시작하였고,
  `OpenAPI` 프로젝트에 참여하여 `API Gateway` 서버를 개발하였습니다.
  해당 `API Gateway` 서버의 역할은 `OpenAPI` 시스템의 중요한 부분을 담당하였습니다.

    - 호출 API Routing 처리
    - API 클라이언트의 권한 인가 및 인증
    - API Access Key 관리
    - API 암호화 Key 관리

  `API Gateway` 서버는 `Spring Cloud Gateway` 프레임워크 기반 새로운 **Reactive Programming** 이란 개발 패러다임을 접목한 개발을 진행하였습니다.
  <br><br>
  **Reactive Programming** 은 기존 선언적 프로그래밍 패러다임과는 다른 개발 방식으로 함수형 프로그래밍 개념부터 반응형 프로그래밍까지 학습을 필요하였고,
  팀원들과 짧은 **함수형/반응형 프로그래밍**과 **Spring Webflux**에 대해 스터디를 진행하면서 기초적인 지식부터 학습하고 함께 공유하였습니다.
  <br><br>
  `Reactor` 객체의 다양한 함수 사용 방법과 더불어 `React-stream` 기반의 `Thread` 관리 방식 등 개발 과정에서 쉽게 넘어가는 일이 없었지만,
  팀원들과 하나씩 해결가면서 개발 요구 사항을 충족하는 `API Gateway` 서버를 끝내 구축할 수 있었습니다.
  그렇게 개발된 `API Gateway` 는 기존 `Spring Cloud Zuul` 기반의 `API Gateway` 에 비해 성능 차이 효과를 확인할 수 있었습니다.
  <br><br>
  함수형 프로그래밍이라는 새로운 개발 패러다임 개발은 익숙하지 않고 힘들었던 점은 분명하였지만,
  개발 과정에서 강조되는 **순수 함수**에 대해 '왜 순수 함수가 더 `Side-effect` 부수 효과를 방지할 수 있는가?',
  **불변성 보장**과 같은 장점이 개발 유지 보수에 어떠한 이점을 가져올 수 있었는지 알게 되었습니다.
  <br><br>
  해당 프로젝트를 진행하면서 개발 외적으로, 새로운 시스템을 구축하는 과정에서 서비스 용도에 맞는 기술 스펙을 선정하는 과정과
  새로운 기술에 대해서는 첫 단추부터 차근차근 채워가는 것이 얼마나 중요한지를 깨닫게 되었습니다.
  또한 성공적인 협업을 위해서 함께 일하는 동료들과 학습해가는 방식과 지식 공유 등 함께 성장할 수 있는 개발의 즐거움도 느끼게 되었습니다.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
